{
 "title": "SETME",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "API 4xx 5xx Errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "ApiName": "SETME-ahd-saocs" },
     "metricName": "4XXError",
     "namespace": "AWS/ApiGateway",
     "region": "eu-central-1",
     "statistics": [ "Sum" ]
    },
    {
     "dimensions": { "ApiName": "SETME-ahd-saocs" },
     "metricName": "5XXError",
     "namespace": "AWS/ApiGateway",
     "region": "eu-central-1",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "4xx Errors",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "alias": "4xx Errors",
     "dimensions": { "ApiName": "SETME-ahd-saocs" },
     "metricName": "4XXError",
     "namespace": "AWS/ApiGateway",
     "region": "eu-central-1",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "API Hits",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "ApiName": "SETME-ahd-saocs" },
     "metricName": "Count",
     "namespace": "AWS/ApiGateway",
     "region": "eu-central-1",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "5xx Errors",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "dimensions": { "ApiName": "SETME-ahd-saocs" },
     "metricName": "5XXError",
     "namespace": "AWS/ApiGateway",
     "region": "eu-central-1",
     "statistics": [ "Sum" ]
    }
   ]
  }
 ]
}